import React from 'react';
import { format } from 'date-fns';

/**
 * Visual Template component showcasing the email design generated by the backend hook.
 * This is useful for admin previews or documentation.
 */
export default function BookingConfirmationEmail({ booking }) {
  if (!booking) return null;

  return (
    <div style={{ fontFamily: 'Arial, sans-serif', maxWidth: '600px', margin: '0 auto', backgroundColor: '#f9fafb' }}>
      {/* Header */}
      <div style={{ backgroundColor: '#ef4444', padding: '30px 40px', textAlign: 'center', borderTopLeftRadius: '8px', borderTopRightRadius: '8px' }}>
        <h1 style={{ color: '#ffffff', margin: 0, fontSize: '24px', letterSpacing: '0.5px' }}>GLOBE EXPRESS LOGISTICS</h1>
      </div>

      {/* Content */}
      <div style={{ backgroundColor: '#ffffff', padding: '40px', borderLeft: '1px solid #e5e7eb', borderRight: '1px solid #e5e7eb' }}>
        <h2 style={{ color: '#111827', marginTop: 0, marginBottom: '20px', fontSize: '20px' }}>Booking Confirmation</h2>
        
        <p style={{ color: '#4b5563', lineHeight: '1.6', marginBottom: '24px' }}>
          Dear {booking.name},<br/><br/>
          Thank you for choosing Globe Express Logistics. We have received your transport request. Below are the details of your booking.
        </p>

        <div style={{ backgroundColor: '#f3f4f6', padding: '20px', borderRadius: '6px', marginBottom: '30px' }}>
          <p style={{ margin: '0 0 10px 0', fontSize: '14px', color: '#6b7280' }}>BOOKING REFERENCE</p>
          <p style={{ margin: 0, fontSize: '22px', fontWeight: 'bold', color: '#111827' }}>{booking.bookingId}</p>
        </div>

        <table style={{ width: '100%', borderCollapse: 'collapse', marginBottom: '30px' }}>
          <tbody>
            <tr>
              <td style={{ padding: '12px 0', borderBottom: '1px solid #e5e7eb', color: '#6b7280', width: '40%' }}>Goods Type</td>
              <td style={{ padding: '12px 0', borderBottom: '1px solid #e5e7eb', color: '#111827', fontWeight: '500' }}>{booking.goodsType}</td>
            </tr>
            <tr>
              <td style={{ padding: '12px 0', borderBottom: '1px solid #e5e7eb', color: '#6b7280' }}>Pickup Date</td>
              <td style={{ padding: '12px 0', borderBottom: '1px solid #e5e7eb', color: '#111827', fontWeight: '500' }}>
                {booking.date ? format(new Date(booking.date), 'MMMM dd, yyyy') : 'N/A'}
              </td>
            </tr>
            <tr>
              <td style={{ padding: '12px 0', borderBottom: '1px solid #e5e7eb', color: '#6b7280' }}>Preferred Time</td>
              <td style={{ padding: '12px 0', borderBottom: '1px solid #e5e7eb', color: '#111827', fontWeight: '500' }}>{booking.time}</td>
            </tr>
          </tbody>
        </table>

        <div style={{ marginBottom: '20px' }}>
          <h3 style={{ color: '#111827', fontSize: '16px', margin: '0 0 10px 0' }}>Pickup Location</h3>
          <p style={{ color: '#4b5563', margin: 0, lineHeight: '1.5' }}>{booking.pickupLocation}</p>
        </div>

        <div>
          <h3 style={{ color: '#111827', fontSize: '16px', margin: '0 0 10px 0' }}>Delivery Location</h3>
          <p style={{ color: '#4b5563', margin: 0, lineHeight: '1.5' }}>{booking.deliveryLocation}</p>
        </div>

        <div style={{ marginTop: '40px', textAlign: 'center' }}>
          <a href={`https://globeexpresslogistics.com/track-booking?id=${booking.bookingId}`} style={{ display: 'inline-block', backgroundColor: '#ef4444', color: '#ffffff', textDecoration: 'none', padding: '12px 24px', borderRadius: '4px', fontWeight: 'bold', fontSize: '14px' }}>
            Track Your Shipment
          </a>
        </div>
      </div>

      {/* Footer */}
      <div style={{ backgroundColor: '#1f2937', padding: '30px 40px', textAlign: 'center', borderBottomLeftRadius: '8px', borderBottomRightRadius: '8px' }}>
        <p style={{ color: '#9ca3af', margin: '0 0 10px 0', fontSize: '14px' }}>
          Globe Express Logistics<br/>
          123 Transport Way, Logistics City, LC 12345
        </p>
        <p style={{ color: '#9ca3af', margin: 0, fontSize: '14px' }}>
          Questions? Contact us at <a href="mailto:support@globeexpresslogistics.com" style={{ color: '#ffc107', textDecoration: 'none' }}>support@globeexpresslogistics.com</a>
        </p>
      </div>
    </div>
  );
}